### ISSUE TITLE
Configure `gh-pages` as "dafault" branch in GitHub

### ISSUE THREAD

**Issue by apetro** [ShaneCurcuru/theapacheway.com#3]
Not a big deal, but it looks to me like `gh-pages` (rather than `master`) ought to be the "default" branch in this project.

This is configurable [in GitHub settings for this project](https://github.com/ShaneCurcuru/theapacheway.com/settings/branches).

Configuring the "main" branch adds a little niceness throughout the GitHub presentation of the repo - defaults branch selector pull-downs, for instance. It also helps set contributor expectations about what branch they should be forking from and proposing merges to.

**Comment by ShaneCurcuru** [comment]
D'oh! Yes, I know that, I just never got around to setting that up here.  Thanks for the note, will put it on my TODO list.

**Comment by apetro** [comment]
I tripped over this defaultness in composing today's "it's" --> "its" fix ( #4  ), initially composing that fix against the not-controlling `master` branch rather than the actually-in-use `gh-pages` branch.

**Comment by ShaneCurcuru** [comment]
Pulled, pushed, merged, and massaged everything to the default 'main' renamed branch.  Since this is just a user-facing website, no need for additional branches.
